### ISSUE TITLE
Deadlock with hackney 1.11

### ISSUE THREAD

**Issue by kuon** [stephenmoloney/fastimage#13]
I open an issue here for reference.

With hackney 1.11 I have a deadlock when I use fastimage, all details here: https://github.com/benoitc/hackney/issues/447#issuecomment-361851611

I am not sure if the bug is in fastimage or hackney itself, but as I don't have the bug with hackney 1.9 I thought it might be hackney.

**Comment by stephenmoloney** [comment]
Fix:

```
error_msg = "error, could not open image file with error #{status_code} due to reason, #{reason}"
raise(error_msg)
```

```
error_msg = "error, could not open image file with error #{status_code} due to reason, #{reason}"
close_stream(stream_ref)
raise(error_msg)
```

**Comment by stephenmoloney** [comment]
I took a closer look at this and there is an issue with hackney version 1.11.0 that I can reproduce in tests. 

I need to take a closer look to figure out exactly what it is though.

@kuon

**Comment by kuon** [comment]
If I can help, just poke me.
