### ISSUE TITLE
review line 66 of the Parser module

### ISSUE THREAD

**Issue by stephenmoloney** [stephenmoloney/fastimage#16]
***Description:***

- review line 66 of the `Parser` module `(# get more data if less that 4 bytes remaining)`
- is it necessary and functioning as expected?

**Comment by ValdesChe** [comment]
Review is necessary here. When trying the package with a small image.  **iex>`Fastimage.info("https://via.placeholder.com/5")`** 
     `** (WithClauseError) no with clause matching: {:error, :nxdomain}
    (fastimage) lib/fastimage.ex:198: Fastimage.get_acc_with_type/3
    (fastimage) lib/fastimage.ex:213:       ######Fastimage.info/3`

**Comment by stephenmoloney** [comment]
I cannot reproduce this. Please check again and verify your internet connection is ok.
#20 is a more relevant issue than this one for this error.
