### ISSUE TITLE
something's wrong with multiple consecutive size/1 calls

### ISSUE THREAD

**Issue by kagux** [stephenmoloney/fastimage#2]
hey, 

first of all,  thanks a lot for your work on this library! 
I wanted to use it to get dimensions for multiple images and noticed that results get mixed up. As in I request sizes for images [....,  A, ... B, .... ] consecutively and often image B size is in fact coming from image A. with delay added between calls less images get affected until it's big enough to disappear completely. 
do you have any ideas why this could be happening?

**Comment by stephenmoloney** [comment]
Hi, can you send me the code sample so I can track it down? 

It's probably something to do with the [stream_chunks_url function](https://github.com/stephenmoloney/fastimage/blob/master/lib/fastimage.ex#L109)

**Comment by stephenmoloney** [comment]
I've tried to reproduce this error you are getting by adding more tests to the test file. 
See [here](https://github.com/kagux/fastimage/pull/2/commits/da0ab4f223fc554cd5ae3096370330fad16c3830).

It doesn't give any errors. 

Is there any way you can gist a sample of where this error arises?

Thanks

**Comment by kagux** [comment]
I'm gonna try to come with a test to reproduce it

**Comment by stephenmoloney** [comment]
Please try with latest version too, thanks!

**Comment by kagux** [comment]
@stephenmoloney, I just did and the issue is gone. Thank you so much!!
