### ISSUE TITLE
Extended WEBP test file is not the correct format

### ISSUE THREAD

**Issue by sneako** [stephenmoloney/fastimage#32]
The files `priv/test_extended.webp` and `priv/test_lossy.webp` are same the type of webp. You will notice that the webp_vp8x function is no longer covered https://coveralls.io/builds/19327754/source?filename=lib%2Ffastimage%2Fparser.ex#L251

**Comment by stephenmoloney** [comment]
I thought I had it right but obviously not.

There must be a way to create the VP8X format with cwebp

https://developers.google.com/speed/webp/docs/cwebp

**Comment by stephenmoloney** [comment]
Fixed by #34
