### ISSUE TITLE
Images aren't processing well

### ISSUE THREAD

**Issue by asiniy** [stephenmoloney/fastimage#9]
I'm trying to process this image via `Fastimage.size(image_path)`: ![20151004001184375674-original](https://cloud.githubusercontent.com/assets/1296472/23752040/36be6b38-04ed-11e7-9311-3cb8f9b64f2e.jpg)

But it returns me exception

``` elixir
iex(3)> Fastimage.size(path)
** (MatchError) no match of right hand side value: ""
    (fastimage) lib/fastimage.ex:257: Fastimage.matching_byte/2
    (fastimage) lib/fastimage.ex:247: Fastimage.next_bytes_until_match/2
    (fastimage) lib/fastimage.ex:159: Fastimage.parse_jpeg/6
    (fastimage) lib/fastimage.ex:190: Fastimage.parse_jpeg/6
    (fastimage) lib/fastimage.ex:187: Fastimage.parse_jpeg/6
    (fastimage) lib/fastimage.ex:190: Fastimage.parse_jpeg/6
    (fastimage) lib/fastimage.ex:187: Fastimage.parse_jpeg/6
    (fastimage) lib/fastimage.ex:190: Fastimage.parse_jpeg/6
    (fastimage) lib/fastimage.ex:43: Fastimage.size/1
```

What should I do here?

**Comment by stephenmoloney** [comment]
This is a bug. I'll see if I can find the issue.

**Comment by stephenmoloney** [comment]
@asiniy 
This is fixed by the [latest commit](https://github.com/stephenmoloney/fastimage/commit/406794e18f5e803eafebaa2ce9b9db51005622ed).

I also made a new release for this change. 
[version 0.0.7](https://hex.pm/packages/fastimage)

**Comment by asiniy** [comment]
@stephenmoloney thanks!
